# Generated by Django 3.0.14 on 2023-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='t_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_fat_saturated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='t_sugar',
            field=models.FloatField(default=0),
        ),
    ]
