# Generated by Django 3.0.14 on 2023-12-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_auto_20231226_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
