# Generated by Django 3.0.14 on 2023-12-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_auto_20231228_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
