# Generated by Django 3.0.14 on 2023-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_auto_20231228_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set',
            field=models.BooleanField(default=False),
        ),
    ]
